/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Vista;

import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import com.mycompany.Modelo.Usuarios;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 * @author pedro Garcia vicente
 */
public class Dashboard extends javax.swing.JFrame {

  private SessionFactory sessionFactory;

  /**
   * Creates new form Dashboard
   */
  //Fondopanel fondo = new Fondopanel();
  public Dashboard() {
    // this.setContentPane(fondo);
    initComponents();
    mostrarpanel(new inicio());
    //btnmenu.putClientProperty("JButton.buttonType", "arc:5");
    UIManager.put("Button.arc", 5);
    /*Configuration configuracion = new Configuration();
    configuracion.configure("/hibernate.cfg.xml");
    this.sessionFactory = configuracion.buildSessionFactory();

    try (Session session = sessionFactory.openSession()) {
      Transaction transaction = session.beginTransaction();

      // Consulta HQL para obtener todos los usuarios
      String hql = "FROM Usuarios";
      Query<Usuarios> query = session.createQuery(hql, Usuarios.class);
      List<Usuarios> usuarios = query.list();
      usuarios.forEach(System.out::println);
      transaction.commit();
    } catch (Exception e) {
      e.printStackTrace();
      // Manejar la excepción según tus necesidades
    }*/

 /* //---- buttonGroup1 ----
    ButtonGroup buttonGroup1 = new ButtonGroup();
    buttonGroup1.add(jToggleButton2);
    buttonGroup1.add(jToggleButton3);
    buttonGroup1.add(jToggleButton4);
    buttonGroup1.add(jToggleButton5);
     */
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnactualizar = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        btninscriequipo = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btninscrientrenador = new javax.swing.JButton();
        btnborrarentre = new javax.swing.JButton();
        btninscrijugadores = new javax.swing.JButton();
        btnactualizarjuga = new javax.swing.JButton();
        frame = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(291, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame-modified.png"))); // NOI18N
        jLabel1.setText("NGALAXYSTAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 47, -1, -1));

        btnactualizar.setBackground(new java.awt.Color(51, 51, 51));
        btnactualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Car.png"))); // NOI18N
        btnactualizar.setText("Actualizar Equipo");
        btnactualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnactualizar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 220, 40));

        btnmenu.setBackground(new java.awt.Color(51, 51, 51));
        btnmenu.setForeground(new java.awt.Color(255, 255, 255));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dashboard.png"))); // NOI18N
        btnmenu.setText("Dashboard");
        btnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 220, 40));

        btninscriequipo.setBackground(new java.awt.Color(51, 51, 51));
        btninscriequipo.setForeground(new java.awt.Color(255, 255, 255));
        btninscriequipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fa-solid_user-edit.png"))); // NOI18N
        btninscriequipo.setText("Inscribir Equipo");
        btninscriequipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninscriequipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btninscriequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninscriequipoActionPerformed(evt);
            }
        });
        jPanel1.add(btninscriequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 40));

        btnlogout.setBackground(new java.awt.Color(51, 51, 51));
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame 39997.png"))); // NOI18N
        btnlogout.setText("Cerrar Sesion");
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 790, 220, 50));

        btninscrientrenador.setBackground(new java.awt.Color(51, 51, 51));
        btninscrientrenador.setForeground(new java.awt.Color(255, 255, 255));
        btninscrientrenador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fa-solid_user-tie.png"))); // NOI18N
        btninscrientrenador.setText("Inscribir entrenador");
        btninscrientrenador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninscrientrenador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btninscrientrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninscrientrenadorActionPerformed(evt);
            }
        });
        jPanel1.add(btninscrientrenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 220, 40));

        btnborrarentre.setBackground(new java.awt.Color(51, 51, 51));
        btnborrarentre.setForeground(new java.awt.Color(255, 255, 255));
        btnborrarentre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fa-solid_user-times.png"))); // NOI18N
        btnborrarentre.setText("Borrar entrenador");
        btnborrarentre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnborrarentre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnborrarentre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarentreActionPerformed(evt);
            }
        });
        jPanel1.add(btnborrarentre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 220, 40));

        btninscrijugadores.setBackground(new java.awt.Color(51, 51, 51));
        btninscrijugadores.setForeground(new java.awt.Color(255, 255, 255));
        btninscrijugadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fa-solid_user-edit.png"))); // NOI18N
        btninscrijugadores.setText("Inscribir Jugadores");
        btninscrijugadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninscrijugadores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btninscrijugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninscrijugadoresActionPerformed(evt);
            }
        });
        jPanel1.add(btninscrijugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 220, 40));

        btnactualizarjuga.setBackground(new java.awt.Color(51, 51, 51));
        btnactualizarjuga.setForeground(new java.awt.Color(255, 255, 255));
        btnactualizarjuga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Car.png"))); // NOI18N
        btnactualizarjuga.setText("Actualizar jugadores");
        btnactualizarjuga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnactualizarjuga.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnactualizarjuga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarjugaActionPerformed(evt);
            }
        });
        jPanel1.add(btnactualizarjuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 220, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout frameLayout = new javax.swing.GroupLayout(frame);
        frame.setLayout(frameLayout);
        frameLayout.setHorizontalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
        );
        frameLayout.setVerticalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 0, 1160, 900));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
    // TODO add your handling code here:
    mostrarpanel(new actuequipo());
  }//GEN-LAST:event_btnactualizarActionPerformed

  private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
    // TODO add your handling code here:
    mostrarpanel(new inicio());
  }//GEN-LAST:event_btnmenuActionPerformed

  private void btninscriequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninscriequipoActionPerformed
    // TODO add your handling code here:
    mostrarpanel(new inscriequipo());
  }//GEN-LAST:event_btninscriequipoActionPerformed

  private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
    // TODO add your handling code here:
    System.exit(0);
  }//GEN-LAST:event_btnlogoutActionPerformed

  private void btninscrientrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninscrientrenadorActionPerformed
    // TODO add your handling code here:
    mostrarpanel(new inscrientrenador());
  }//GEN-LAST:event_btninscrientrenadorActionPerformed

  private void btnborrarentreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarentreActionPerformed
    // TODO add your handling code here:
    mostrarpanel(new borrarentrenador());
  }//GEN-LAST:event_btnborrarentreActionPerformed

  private void btninscrijugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninscrijugadoresActionPerformed
    // TODO add your handling code here:
    mostrarpanel(new inscrijugador());
  }//GEN-LAST:event_btninscrijugadoresActionPerformed

  private void btnactualizarjugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarjugaActionPerformed
    // TODO add your handling code here:
    mostrarpanel(new actujugador());
  }//GEN-LAST:event_btnactualizarjugaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    FlatLightFlatIJTheme.setup();

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Dashboard().setVisible(true);
      }
    });
  }

  private void mostrarpanel(JPanel p) {
    p.setSize(1160, 900);
    p.setLocation(0, 0);

    frame.removeAll();
    frame.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    frame.revalidate();
    frame.repaint();
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnactualizarjuga;
    private javax.swing.JButton btnborrarentre;
    private javax.swing.JButton btninscrientrenador;
    private javax.swing.JButton btninscriequipo;
    private javax.swing.JButton btninscrijugadores;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmenu;
    private javax.swing.JPanel frame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
