/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.Vista;

import com.mycompany.Controlador.sqlhelpertablas;
import com.mycompany.Modelo.Entrenadores;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import com.mycompany.Modelo.Equipo;
import com.mycompany.Modelo.Jugadores;
import java.util.Set;

/**
 *
 * @author pedro Garcia vicente
 */
public class inicio extends javax.swing.JPanel {

  /**
   * Creates new form inicio
   */
  Fondopanel fondo = new Fondopanel();

  public inicio() {
    //this.setContentPane(fondo);
    sqlhelpertablas sql = new sqlhelpertablas();
    initComponents();
    String textoreglas = "<html><p>1.Solo se podra inscribir un equipo por presidente no puedes ser dueño de dos equipos.</p>"+"<p></p>"
      + "2.Los presidentes seran quienes inscriban a su equipo con los datos que se pidan.\n" +"<p></p>"
      + "3.No podras incribir a un entrenador si no has inscrito primero al equipo.\n"+"<p></p>"
      + "<p>4.Si se lesiona algun jugador,ese equipo podra fichar a otro jugador para sustituirlo.</p>"+"<p></p>"
      + "<p>5.Los estadios tienen que cumplir las medidas y seguridades por la policia y el propio torneo.</p></html>";
    labelreglas.setText(textoreglas);
    
    //tabla equipos
    List<Equipo> lista = sql.selectEquipos();
    DefaultTableModel tableModel = (DefaultTableModel) Tablaequipos.getModel();
    for (Equipo e : lista) {
    for (Entrenadores entrenador : e.getEntrenadoreses()) {
        tableModel.addRow(new Object[]{
            e.getNombreEquipo(),
            e.getCiudad(),
            e.getEstadio(),
            entrenador.getNombreCompletoentrenador(),
            entrenador.getClocalColor(),
            entrenador.getCvisitanteColor()
        });
    }
}
    //tabla jugadores
    List<Jugadores> listaa = sql.selectjugadores();
    DefaultTableModel tableModel1 = (DefaultTableModel) tablajugadores.getModel();
    
    for (Jugadores j : listaa) {   
    tableModel1.addRow(new Object[]{
            j.getEquipo().getNombreEquipo(),
            j.getNombrejugador(),
            j.getDorsal(),
        });
}


// Notifica a la tabla que se han realizado cambios en el modelo
    tableModel.fireTableDataChanged();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Fondopanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelreglas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablaequipos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablajugadores = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1160, 900));

        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 900));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reglas");

        labelreglas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelreglas.setForeground(new java.awt.Color(255, 255, 255));
        labelreglas.setText("jLabel2");

        Tablaequipos.setBackground(new java.awt.Color(51, 51, 51));
        Tablaequipos.setForeground(new java.awt.Color(255, 255, 255));
        Tablaequipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N.Equipo", "Ciudad", "Estadio", "N.Entrenador", "cLocalColor", "cVisitanteColor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tablaequipos);
        if (Tablaequipos.getColumnModel().getColumnCount() > 0) {
            Tablaequipos.getColumnModel().getColumn(1).setResizable(false);
            Tablaequipos.getColumnModel().getColumn(2).setResizable(false);
        }

        tablajugadores.setBackground(new java.awt.Color(51, 51, 51));
        tablajugadores.setForeground(new java.awt.Color(255, 255, 255));
        tablajugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "N.Equipo", "Jugador", "Dorsal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablajugadores);
        if (tablajugadores.getColumnModel().getColumnCount() > 0) {
            tablajugadores.getColumnModel().getColumn(0).setResizable(false);
            tablajugadores.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelreglas, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelreglas, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablaequipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelreglas;
    private javax.swing.JTable tablajugadores;
    // End of variables declaration//GEN-END:variables
 
  /**
   * Esta clase es para meter una foto en un panel
   */
  class Fondopanel extends JPanel {

    private Image imagen;

    public void paint(Graphics g) {
      imagen = new ImageIcon(getClass().getResource("/img/fondopaneles2.jpg")).getImage();
      g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

      setOpaque(false);

      super.paint(g);
    }
  }
}
