/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Vista;

import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import com.mycompany.Controlador.sqlhelperloginregister;
import com.mycompany.Modelo.Usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro Garcia vicente
 */
public class Registro extends javax.swing.JFrame {

  private iniciosesion ini;
  private Usuarios usu;
  private sqlhelperloginregister sql = new sqlhelperloginregister();

  /**
   * Creates new form Registro
   */
  public Registro() {
    initComponents();
    labelcreateaccount.putClientProperty("FlatLaf.style", "font: $h0.font");

    tfusername.putClientProperty("FlatLaf.style", "arc:" + 12);
    // UIManager.put( "TextComponent.arc", 999 );
    tfusername.putClientProperty("JTextField.placeholderText", "Introduzca usuario");

    tfpassword.putClientProperty("FlatLaf.style", "arc:" + 12);
    tfpassword.putClientProperty("JTextField.placeholderText", "Introduzca contraseña");

    btnregi.putClientProperty("JButton.buttonType", "roundRect");
    btnvolver.putClientProperty("JButton.buttonType", "roundRect");

    tfnombre.putClientProperty("FlatLaf.style", "arc:" + 12);
    tfnombre.putClientProperty("JTextField.placeholderText", "Introduzca Nombre");

    tfapellidos.putClientProperty("FlatLaf.style", "arc:" + 12);
    tfapellidos.putClientProperty("JTextField.placeholderText", "Introduzca Apellidos");

    tfemail.putClientProperty("FlatLaf.style", "arc:" + 12);
    tfemail.putClientProperty("JTextField.placeholderText", "Introduzca Email");

  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    tfemail = new javax.swing.JTextField();
    tfusername = new javax.swing.JTextField();
    labeltitulo = new javax.swing.JLabel();
    tfapellidos = new javax.swing.JTextField();
    btnregi = new javax.swing.JButton();
    labelcreateaccount = new javax.swing.JLabel();
    tfnombre = new javax.swing.JTextField();
    tfpassword = new javax.swing.JTextField();
    btnvolver = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    labeltitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    labeltitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NGALAXYSTARf.png"))); // NOI18N

    btnregi.setBackground(new java.awt.Color(75, 6, 99));
    btnregi.setForeground(new java.awt.Color(255, 255, 255));
    btnregi.setText("Registrarse");
    btnregi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnregi.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnregiActionPerformed(evt);
      }
    });

    labelcreateaccount.setText("Create My Account");

    btnvolver.setBackground(new java.awt.Color(75, 6, 99));
    btnvolver.setForeground(new java.awt.Color(255, 255, 255));
    btnvolver.setText("Volver");
    btnvolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnvolver.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnvolverActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(106, 106, 106)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(tfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(tfapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGap(0, 96, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labeltitulo)
          .addComponent(labelcreateaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(27, 27, 27))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnregi, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(41, 41, 41))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addComponent(labeltitulo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(labelcreateaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(48, 48, 48)
        .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(64, 64, 64)
        .addComponent(tfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(64, 64, 64)
        .addComponent(tfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(64, 64, 64)
        .addComponent(tfapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(64, 64, 64)
        .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(48, 48, 48)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnregi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(127, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnregiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregiActionPerformed
    // TODO add your handling code here:
    String user = tfusername.getText();
    String cont = tfpassword.getText();
    String correo = tfemail.getText();
    String nombre = tfnombre.getText();
    String apellido = tfapellidos.getText();
    if (user.isEmpty() || cont.isEmpty() || correo.isEmpty() || nombre.isEmpty() || apellido.isEmpty()) {
      JOptionPane.showMessageDialog(rootPane, "Por favor, completa todos los campos", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
    } else {
      try {
        boolean comprueba = sql.verificarCredenciales(user, cont, correo);
        if (comprueba == true) {
          JOptionPane.showMessageDialog(rootPane, "El usuario o email ya existe en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
          tfusername.setText("");
          tfpassword.setText("");
          tfemail.setText("");
        } else {
          sql.introducirUsuario(user, cont, correo, nombre, apellido);
          JOptionPane.showMessageDialog(rootPane, "Usuario Creado correctamente");
          tfusername.setText("");
          tfpassword.setText("");
          tfemail.setText("");
          tfnombre.setText("");
          tfapellidos.setText("");

          ini = new iniciosesion();
          ini.setVisible(true);
          dispose();
        }
      } catch (ClassCastException e) {
        e.printStackTrace();
      }
    }

  }//GEN-LAST:event_btnregiActionPerformed

  private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
    // TODO add your handling code here:
    ini = new iniciosesion();
    ini.setVisible(true);
    dispose();
  }//GEN-LAST:event_btnvolverActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    FlatLightFlatIJTheme.setup();

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Registro().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnregi;
  private javax.swing.JButton btnvolver;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel labelcreateaccount;
  private javax.swing.JLabel labeltitulo;
  private javax.swing.JTextField tfapellidos;
  private javax.swing.JTextField tfemail;
  private javax.swing.JTextField tfnombre;
  private javax.swing.JTextField tfpassword;
  private javax.swing.JTextField tfusername;
  // End of variables declaration//GEN-END:variables
}
