package modelo;
// Generated 18 dic 2023 18:15:45 by Hibernate Tools 6.3.1.Final

/**
 * Entrenadores generated by hbm2java
 */
public class Entrenadores implements java.io.Serializable {

	private Integer id;
	private Equipo equipo;
	private String nombreCompletoentrenador;
	private String clocalColor;
	private String cvisitanteColor;

	public Entrenadores() {
	}

	public Entrenadores(Equipo equipo, String nombreCompletoentrenador, String clocalColor, String cvisitanteColor) {
		this.equipo = equipo;
		this.nombreCompletoentrenador = nombreCompletoentrenador;
		this.clocalColor = clocalColor;
		this.cvisitanteColor = cvisitanteColor;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	public String getNombreCompletoentrenador() {
		return this.nombreCompletoentrenador;
	}

	public void setNombreCompletoentrenador(String nombreCompletoentrenador) {
		this.nombreCompletoentrenador = nombreCompletoentrenador;
	}

	public String getClocalColor() {
		return this.clocalColor;
	}

	public void setClocalColor(String clocalColor) {
		this.clocalColor = clocalColor;
	}

	public String getCvisitanteColor() {
		return this.cvisitanteColor;
	}

	public void setCvisitanteColor(String cvisitanteColor) {
		this.cvisitanteColor = cvisitanteColor;
	}

}
