package modelo;
// Generated 18 dic 2023 18:15:45 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo implements java.io.Serializable {

	private Integer idEquipo;
	private Usuarios usuarios;
	private String nombreEquipo;
	private String ciudad;
	private String estadio;
	private Set jugadoreses = new HashSet(0);
	private Set entrenadoreses = new HashSet(0);

	public Equipo() {
	}

	public Equipo(Usuarios usuarios, String nombreEquipo, String ciudad, String estadio, Set jugadoreses,
			Set entrenadoreses) {
		this.usuarios = usuarios;
		this.nombreEquipo = nombreEquipo;
		this.ciudad = ciudad;
		this.estadio = estadio;
		this.jugadoreses = jugadoreses;
		this.entrenadoreses = entrenadoreses;
	}

	public Integer getIdEquipo() {
		return this.idEquipo;
	}

	public void setIdEquipo(Integer idEquipo) {
		this.idEquipo = idEquipo;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public String getNombreEquipo() {
		return this.nombreEquipo;
	}

	public void setNombreEquipo(String nombreEquipo) {
		this.nombreEquipo = nombreEquipo;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getEstadio() {
		return this.estadio;
	}

	public void setEstadio(String estadio) {
		this.estadio = estadio;
	}

	public Set getJugadoreses() {
		return this.jugadoreses;
	}

	public void setJugadoreses(Set jugadoreses) {
		this.jugadoreses = jugadoreses;
	}

	public Set getEntrenadoreses() {
		return this.entrenadoreses;
	}

	public void setEntrenadoreses(Set entrenadoreses) {
		this.entrenadoreses = entrenadoreses;
	}

}
