package modelo;
// Generated 18 dic 2023 18:15:45 by Hibernate Tools 6.3.1.Final

/**
 * Jugadores generated by hbm2java
 */
public class Jugadores implements java.io.Serializable {

	private Integer idjugador;
	private Equipo equipo;
	private String nombrejugador;
	private int dorsal;

	public Jugadores() {
	}

	public Jugadores(Equipo equipo, String nombrejugador, int dorsal) {
		this.equipo = equipo;
		this.nombrejugador = nombrejugador;
		this.dorsal = dorsal;
	}

	public Integer getIdjugador() {
		return this.idjugador;
	}

	public void setIdjugador(Integer idjugador) {
		this.idjugador = idjugador;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	public String getNombrejugador() {
		return this.nombrejugador;
	}

	public void setNombrejugador(String nombrejugador) {
		this.nombrejugador = nombrejugador;
	}

	public int getDorsal() {
		return this.dorsal;
	}

	public void setDorsal(int dorsal) {
		this.dorsal = dorsal;
	}

}
