package modelo;
// Generated 18 dic 2023 18:15:45 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer id;
	private String usuario;
	private String contrasena;
	private String email;
	private String nombre;
	private String apellidos;
	private Set equipos = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(String usuario, String contrasena, String email, String nombre, String apellidos, Set equipos) {
		this.usuario = usuario;
		this.contrasena = contrasena;
		this.email = email;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.equipos = equipos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Set getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Set equipos) {
		this.equipos = equipos;
	}

}
